use clap::Parser;

#[derive(Parser)]
pub struct Arguments {
    /// The name of a phase whose output to print. This can be supplied multiple times. Accepted values are "lexer", "parser", "simplifier", "typechecker", or "jit_compiler"
    #[arg(long)]
    pub debug_phase: Vec<String>,

    /// If supplied, print the stack map generated by LLVM in a human-readable format.
    #[arg(long)]
    pub print_stack_map: bool,
}
